// Explicit release packet IDs and argument registries, not a numeric range guess.
fn legacy_capabilities(number: i32) -> Option<SwitchingCapabilities> {
    Some(match number {
        // 1.8.9
        47 => SwitchingCapabilities {
            join_game: 0x1,
            commands: -1,
            bundle_delimiter: -1,
            play_information: 0x15,
            play_payload: 0x17,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x1,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0x2,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.9, 1.9.1, 1.9.2, 1.9.4, 1.10.2, 1.11, 1.11.2, 1.12.1, 1.12.2
        107 | 108 | 109 | 110 | 210 | 315 | 316 | 338 | 340 => SwitchingCapabilities {
            join_game: 0x23,
            commands: -1,
            bundle_delimiter: -1,
            play_information: 0x4,
            play_payload: 0x9,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x2,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xf,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.12
        335 => SwitchingCapabilities {
            join_game: 0x23,
            commands: -1,
            bundle_delimiter: -1,
            play_information: 0x5,
            play_payload: 0xa,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x3,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xf,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.13, 1.13.1, 1.13.2
        393 | 401 | 404 => SwitchingCapabilities {
            join_game: 0x25,
            commands: 0x11,
            bundle_delimiter: -1,
            play_information: 0x4,
            play_payload: 0xa,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x2,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xe,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.14, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.16, 1.16.1
        477 | 480 | 485 | 490 | 498 | 735 | 736 => SwitchingCapabilities {
            join_game: 0x25,
            commands: 0x11,
            bundle_delimiter: -1,
            play_information: 0x5,
            play_payload: 0xb,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x3,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xe,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.15, 1.15.1, 1.15.2
        573 | 575 | 578 => SwitchingCapabilities {
            join_game: 0x26,
            commands: 0x12,
            bundle_delimiter: -1,
            play_information: 0x5,
            play_payload: 0xb,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x3,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xf,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.16.2, 1.16.3, 1.16.5
        751 | 753 | 754 => SwitchingCapabilities {
            join_game: 0x24,
            commands: 0x10,
            bundle_delimiter: -1,
            play_information: 0x5,
            play_payload: 0xb,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x3,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xe,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.17, 1.17.1, 1.18.1, 1.18.2
        755..=758 => SwitchingCapabilities {
            join_game: 0x26,
            commands: 0x12,
            bundle_delimiter: -1,
            play_information: 0x5,
            play_payload: 0xa,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: 0x3,
            signed_command: -1,
            chat_acknowledgement: -1,
            system_chat: 0xf,
            score_holder_parser: 0x1f,
            time_parser: -1,
            first_resource_parser: 0x2c,
            last_resource_parser: 0x2c,
            last_parser: 0x38,
            ..V1_21
        },
        // 1.19
        759 => SwitchingCapabilities {
            join_game: 0x23,
            commands: 0xf,
            bundle_delimiter: -1,
            play_information: 0x7,
            play_payload: 0xc,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: -1,
            signed_command: 0x3,
            chat_acknowledgement: -1,
            system_chat: 0x5f,
            score_holder_parser: 0x1d,
            time_parser: -1,
            first_resource_parser: 0x2b,
            last_resource_parser: 0x2c,
            last_parser: 0x2f,
            ..V1_21
        },
        // 1.19.2
        760 => SwitchingCapabilities {
            join_game: 0x25,
            commands: 0xf,
            bundle_delimiter: -1,
            play_information: 0x8,
            play_payload: 0xd,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: -1,
            signed_command: 0x4,
            chat_acknowledgement: 0x3,
            system_chat: 0x62,
            score_holder_parser: 0x1d,
            time_parser: -1,
            first_resource_parser: 0x2b,
            last_resource_parser: 0x2c,
            last_parser: 0x2f,
            ..V1_21
        },
        // 1.19.3
        761 => SwitchingCapabilities {
            join_game: 0x24,
            commands: 0xe,
            bundle_delimiter: -1,
            play_information: 0x7,
            play_payload: 0xc,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: -1,
            signed_command: 0x4,
            chat_acknowledgement: 0x3,
            system_chat: 0x60,
            score_holder_parser: 0x1d,
            time_parser: -1,
            first_resource_parser: 0x29,
            last_resource_parser: 0x2c,
            last_parser: 0x2f,
            ..V1_21
        },
        // 1.19.4, 1.20.1
        762 | 763 => SwitchingCapabilities {
            join_game: 0x28,
            commands: 0x10,
            bundle_delimiter: 0x0,
            play_information: 0x8,
            play_payload: 0xd,
            config_information: -1,
            config_payload: -1,
            config_pack_pop: -1,
            command: -1,
            signed_command: 0x4,
            chat_acknowledgement: 0x3,
            system_chat: 0x64,
            score_holder_parser: 0x1d,
            time_parser: 0x28,
            first_resource_parser: 0x29,
            last_resource_parser: 0x2c,
            last_parser: 0x30,
            ..V1_21
        },
        // 1.20.2
        764 => SwitchingCapabilities {
            join_game: 0x29,
            commands: 0x11,
            bundle_delimiter: 0x0,
            play_information: 0x9,
            play_payload: 0xf,
            config_information: 0x0,
            config_payload: 0x1,
            config_pack_pop: -1,
            command: -1,
            signed_command: 0x4,
            chat_acknowledgement: 0x3,
            system_chat: 0x67,
            score_holder_parser: 0x1d,
            time_parser: 0x28,
            first_resource_parser: 0x29,
            last_resource_parser: 0x2c,
            last_parser: 0x30,
            ..V1_21
        },
        // 1.20.4
        765 => SwitchingCapabilities {
            join_game: 0x29,
            commands: 0x11,
            bundle_delimiter: 0x0,
            play_information: 0x9,
            play_payload: 0x10,
            config_information: 0x0,
            config_payload: 0x1,
            config_pack_pop: 0x6,
            command: -1,
            signed_command: 0x4,
            chat_acknowledgement: 0x3,
            system_chat: 0x69,
            score_holder_parser: 0x1e,
            time_parser: 0x29,
            first_resource_parser: 0x2a,
            last_resource_parser: 0x2d,
            last_parser: 0x31,
            ..V1_21
        },
        // 1.20.6
        766 => SwitchingCapabilities {
            join_game: 0x2b,
            commands: 0x11,
            bundle_delimiter: 0x0,
            play_information: 0xa,
            play_payload: 0x12,
            config_information: 0x0,
            config_payload: 0x2,
            config_pack_pop: 0x8,
            command: 0x4,
            signed_command: 0x5,
            chat_acknowledgement: 0x3,
            system_chat: 0x6c,
            score_holder_parser: 0x1e,
            time_parser: 0x2a,
            first_resource_parser: 0x2b,
            last_resource_parser: 0x2e,
            last_parser: 0x35,
            ..V1_21
        },
        _ => return None,
    })
}

fn named_parser(name: &str) -> io::Result<i32> {
    Ok(match name {
        "brigadier:bool" => 0,
        "brigadier:double" => 2,
        "brigadier:float" => 1,
        "brigadier:integer" => 3,
        "brigadier:long" => 4,
        "brigadier:string" => 5,
        "minecraft:angle" => 50,
        "minecraft:block_pos" => 50,
        "minecraft:block_predicate" => 50,
        "minecraft:block_state" => 50,
        "minecraft:color" => 50,
        "minecraft:column_pos" => 50,
        "minecraft:component" => 50,
        "minecraft:dimension" => 50,
        "minecraft:entity" => 6,
        "minecraft:entity_anchor" => 50,
        "minecraft:entity_summon" => 50,
        "minecraft:float_range" => 50,
        "minecraft:function" => 50,
        "minecraft:game_profile" => 50,
        "minecraft:int_range" => 50,
        "minecraft:item_enchantment" => 50,
        "minecraft:item_predicate" => 50,
        "minecraft:item_slot" => 50,
        "minecraft:item_stack" => 50,
        "minecraft:message" => 50,
        "minecraft:mob_effect" => 50,
        "minecraft:nbt" => 50,
        "minecraft:nbt_compound_tag" => 50,
        "minecraft:nbt_path" => 50,
        "minecraft:objective" => 50,
        "minecraft:objective_criteria" => 50,
        "minecraft:operation" => 50,
        "minecraft:particle" => 50,
        "minecraft:range" => 6,
        "minecraft:resource" => 44,
        "minecraft:resource_location" => 50,
        "minecraft:resource_or_tag" => 44,
        "minecraft:rotation" => 50,
        "minecraft:score_holder" => 31,
        "minecraft:scoreboard_slot" => 50,
        "minecraft:swizzle" => 50,
        "minecraft:team" => 50,
        "minecraft:time" => 50,
        "minecraft:uuid" => 50,
        "minecraft:vec2" => 50,
        "minecraft:vec3" => 50,
        _ => return Err(invalid("unknown named command parser")),
    })
}
